#############################################################################
# Makefile for building: Chess-bluetooth
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  Chess-bluetooth.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Chess-bluetooth.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_BLUETOOTH_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -Isrc -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtBluetooth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtDBus -I/usr/include/qt6/QtCore -I. -I/usr/lib64/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Chess-bluetooth1.0.0
DISTDIR = /home/tahmid/programming_files/Chess-bluetooth/.tmp/Chess-bluetooth1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib64/libQt6Widgets.so /usr/lib64/libQt6Gui.so /usr/lib64/libQt6Bluetooth.so /usr/lib64/libQt6Network.so /usr/lib64/libQt6DBus.so /usr/lib64/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/chessboard.cpp \
		src/chessai.cpp \
		src/bluetoothmanager.cpp \
		src/bluetoothdialog.cpp qrc_chess.cpp \
		moc_mainwindow.cpp \
		moc_chessboard.cpp \
		moc_bluetoothmanager.cpp \
		moc_bluetoothdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		chessboard.o \
		chessai.o \
		bluetoothmanager.o \
		bluetoothdialog.o \
		qrc_chess.o \
		moc_mainwindow.o \
		moc_chessboard.o \
		moc_bluetoothmanager.o \
		moc_bluetoothdialog.o
DIST          = /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/dbuscommon.pri \
		/usr/lib64/qt6/mkspecs/features/dbusinterfaces.prf \
		/usr/lib64/qt6/mkspecs/features/dbusadaptors.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		Chess-bluetooth.pro src/mainwindow.h \
		src/chessboard.h \
		src/chessai.h \
		src/bluetoothmanager.h \
		src/bluetoothdialog.h src/main.cpp \
		src/mainwindow.cpp \
		src/chessboard.cpp \
		src/chessai.cpp \
		src/bluetoothmanager.cpp \
		src/bluetoothdialog.cpp
QMAKE_TARGET  = Chess-bluetooth
DESTDIR       = 
TARGET        = Chess-bluetooth


first: all
####### Build rules

Chess-bluetooth:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Chess-bluetooth.pro /usr/lib64/qt6/mkspecs/linux-g++/qmake.conf /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/dbuscommon.pri \
		/usr/lib64/qt6/mkspecs/features/dbusinterfaces.prf \
		/usr/lib64/qt6/mkspecs/features/dbusadaptors.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		Chess-bluetooth.pro \
		resources/chess.qrc \
		/usr/lib64/libQt6Widgets.prl \
		/usr/lib64/libQt6Gui.prl \
		/usr/lib64/libQt6Bluetooth.prl \
		/usr/lib64/libQt6Network.prl \
		/usr/lib64/libQt6DBus.prl \
		/usr/lib64/libQt6Core.prl
	$(QMAKE) -o Makefile Chess-bluetooth.pro
/usr/lib64/qt6/mkspecs/features/spec_pre.prf:
/usr/lib64/qt6/mkspecs/common/unix.conf:
/usr/lib64/qt6/mkspecs/common/linux.conf:
/usr/lib64/qt6/mkspecs/common/sanitize.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt6/mkspecs/common/g++-base.conf:
/usr/lib64/qt6/mkspecs/common/g++-unix.conf:
/usr/lib64/qt6/mkspecs/qconfig.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_connectivity_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt6/mkspecs/features/qt_functions.prf:
/usr/lib64/qt6/mkspecs/features/qt_config.prf:
/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt6/mkspecs/features/toolchain.prf:
/usr/lib64/qt6/mkspecs/features/default_pre.prf:
/usr/lib64/qt6/mkspecs/features/resolve_config.prf:
/usr/lib64/qt6/mkspecs/features/default_post.prf:
/usr/lib64/qt6/mkspecs/features/warn_on.prf:
/usr/lib64/qt6/mkspecs/features/permissions.prf:
/usr/lib64/qt6/mkspecs/features/qt.prf:
/usr/lib64/qt6/mkspecs/features/resources_functions.prf:
/usr/lib64/qt6/mkspecs/features/resources.prf:
/usr/lib64/qt6/mkspecs/features/moc.prf:
/usr/lib64/qt6/mkspecs/features/dbuscommon.pri:
/usr/lib64/qt6/mkspecs/features/dbusinterfaces.prf:
/usr/lib64/qt6/mkspecs/features/dbusadaptors.prf:
/usr/lib64/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt6/mkspecs/features/uic.prf:
/usr/lib64/qt6/mkspecs/features/unix/thread.prf:
/usr/lib64/qt6/mkspecs/features/qmake_use.prf:
/usr/lib64/qt6/mkspecs/features/file_copies.prf:
/usr/lib64/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt6/mkspecs/features/exceptions.prf:
/usr/lib64/qt6/mkspecs/features/yacc.prf:
/usr/lib64/qt6/mkspecs/features/lex.prf:
Chess-bluetooth.pro:
resources/chess.qrc:
/usr/lib64/libQt6Widgets.prl:
/usr/lib64/libQt6Gui.prl:
/usr/lib64/libQt6Bluetooth.prl:
/usr/lib64/libQt6Network.prl:
/usr/lib64/libQt6DBus.prl:
/usr/lib64/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Chess-bluetooth.pro

qmake_all: FORCE


all: Makefile Chess-bluetooth

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/chess.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/chessboard.h src/chessai.h src/bluetoothmanager.h src/bluetoothdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/chessboard.cpp src/chessai.cpp src/bluetoothmanager.cpp src/bluetoothdialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_chess.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_chess.cpp
qrc_chess.cpp: resources/chess.qrc \
		/usr/lib64/qt6/libexec/rcc \
		resources/Asset\ Images/QW.png \
		resources/Asset\ Images/NB.png \
		resources/Asset\ Images/KB.png \
		resources/Asset\ Images/BW.png \
		resources/Asset\ Images/BB.png \
		resources/Asset\ Images/RW.png \
		resources/Asset\ Images/NW.png \
		resources/Asset\ Images/KW.png \
		resources/Asset\ Images/PB.png \
		resources/Asset\ Images/RB.png \
		resources/Asset\ Images/PW.png \
		resources/Asset\ Images/QB.png
	/usr/lib64/qt6/libexec/rcc -name chess resources/chess.qrc -o qrc_chess.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib64/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_chessboard.cpp moc_bluetoothmanager.cpp moc_bluetoothdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_chessboard.cpp moc_bluetoothmanager.cpp moc_bluetoothdialog.cpp
moc_mainwindow.cpp: src/mainwindow.h \
		src/chessboard.h \
		src/chessai.h \
		src/bluetoothmanager.h \
		src/bluetoothdialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/tahmid/programming_files/Chess-bluetooth/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth/src -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtBluetooth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtDBus -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

moc_chessboard.cpp: src/chessboard.h \
		src/chessai.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/tahmid/programming_files/Chess-bluetooth/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth/src -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtBluetooth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtDBus -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include src/chessboard.h -o moc_chessboard.cpp

moc_bluetoothmanager.cpp: src/bluetoothmanager.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/tahmid/programming_files/Chess-bluetooth/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth/src -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtBluetooth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtDBus -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include src/bluetoothmanager.h -o moc_bluetoothmanager.cpp

moc_bluetoothdialog.cpp: src/bluetoothdialog.h \
		src/bluetoothmanager.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/tahmid/programming_files/Chess-bluetooth/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth -I/home/tahmid/programming_files/Chess-bluetooth/src -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtBluetooth -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtDBus -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-redhat-linux -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-redhat-linux/15/include -I/usr/local/include -I/usr/include src/bluetoothdialog.h -o moc_bluetoothdialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/chessboard.h \
		src/chessai.h \
		src/bluetoothmanager.h \
		src/bluetoothdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/chessboard.h \
		src/chessai.h \
		src/bluetoothmanager.h \
		src/bluetoothdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

chessboard.o: src/chessboard.cpp src/chessboard.h \
		src/chessai.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chessboard.o src/chessboard.cpp

chessai.o: src/chessai.cpp src/chessai.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chessai.o src/chessai.cpp

bluetoothmanager.o: src/bluetoothmanager.cpp src/bluetoothmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bluetoothmanager.o src/bluetoothmanager.cpp

bluetoothdialog.o: src/bluetoothdialog.cpp src/bluetoothdialog.h \
		src/bluetoothmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bluetoothdialog.o src/bluetoothdialog.cpp

qrc_chess.o: qrc_chess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_chess.o qrc_chess.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_chessboard.o: moc_chessboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chessboard.o moc_chessboard.cpp

moc_bluetoothmanager.o: moc_bluetoothmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bluetoothmanager.o moc_bluetoothmanager.cpp

moc_bluetoothdialog.o: moc_bluetoothdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bluetoothdialog.o moc_bluetoothdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

